---
- name: App_asu prep | Make dir for app
  file:
    path: "{{def_app_asu_dir}}"
    state: directory
    mode: '0777'

- name: App_asu prep | Dir for nginx
  file:
    path: "{{def_app_asu_dir}}/nginx-config/conf.d/"
    state: directory
    mode: '0777'

- name: App_asu prep | copy conf files
  template:
    src: '{{ item.src }}'
    dest: "{{def_app_asu_dir}}/{{ item.path | regex_replace('.j2$', '') }}"
  with_filetree: ../templates/
  become: yes
  when: item.state == 'file'

- name: App_asu prep | Move def.conf for nginx
  command: mv "{{def_app_asu_dir}}/default.conf" "{{def_app_asu_dir}}/nginx-config/conf.d/default.conf"

- name: App_asu prep | Create Logs dir
  file:
    path: "{{def_app_asu_dir}}/Logs"
    state: directory

- name: App_asu prep | Create database for app_asu
  become_user: postgres
  postgresql_db: 
    login_unix_socket: /tmp
    name: "{{pg_app_asu_name}}"