---
- name: App_asu docker dir | Change docker home dir if not eough space
  file:
    path: "{{ item.path }}" 
    mode: '0777'
    state: "{{ item.state }}"
  loop:
    - { path: '/etc/docker/', state: 'directory' }
    - { path: '/home/docker/', state: 'directory' }

- name: App_asu docker dir | Copy daemon.json from template for docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: App_asu docker dir | Reload Daemon
  command: systemctl daemon-reload

- name: App_asu docker dir | Reload docker service
  service:
    name: docker
    state: restarted