---
- name: Add exporter group
  group:
    name: "{{exporter_name}}"
    state: present

- name: Add exporter user
  user:
    name: "{{exporter_name}}"
    shell: /bin/false
    groups: "{{exporter_name}}"
    append: true

- name: Download
  get_url:
    url: "{{exporter_url}}" 
    dest: "/home/{{ansible_user}}/{{exporter_name}}"

- name: Unpack
  unarchive:
    src: "/home/{{ansible_user}}/{{exporter_name}}"
    dest: "/home/{{ansible_user}}/"
    remote_src: yes
    list_files: yes
    extra_opts:
      - "--no-anchored"
      - "{{exporter_name}}"
  register: unarchived_list

- name: Cp
  copy:
    src: "/home/{{ansible_user}}/{{unarchived_list.files[0]}}"
    dest: "/usr/bin/{{exporter_name}}"
    owner: "{{exporter_name}}"
    group: "{{exporter_name}}"
    mode: '755'
    remote_src: yes
  
- name: Create service
  template:
    src: ../templates/exporter.service.j2
    dest: "/etc/systemd/system/{{exporter_name}}.service"
  become: yes

- name: Ensure the service is running
  become: true
  systemd:
    daemon-reload: true
    name: "{{exporter_name}}.service"
    enabled: true
    state: started